version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    working_dir: /app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    working_dir: /app
    environment:
      - NODE_ENV=production
