name: Manual Deploy (Placeholder)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g. staging, production)'
        required: true
        default: 'staging'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Frontend deps
        working-directory: Frontend
        run: npm ci || npm install
      - name: Build Frontend
        working-directory: Frontend
        run: npm run build
      - name: Install Admin deps
        working-directory: admin
        run: npm ci || npm install
      - name: Build Admin
        working-directory: admin
        run: npm run build || echo "No admin build script yet"
      - name: Archive frontend dist (if present)
        run: |
          if [ -d Frontend/dist ]; then tar -czf frontend-dist.tar.gz -C Frontend dist; else echo "No Frontend/dist yet"; fi
      - name: Archive admin dist (if present)
        run: |
          if [ -d admin/dist ]; then tar -czf admin-dist.tar.gz -C admin dist; else echo "No admin/dist yet"; fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-builds
          path: |
            frontend-dist.tar.gz
            admin-dist.tar.gz
  note:
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - name: Reminder
        run: echo "Add Docker + real deployment steps later (e.g., push images, deploy to host)."